# Generated by Django 2.2.2 on 2019-06-12 00:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('fecha', models.DateField(db_column='fecha')),
                ('total', models.IntegerField(db_column='total')),
                ('observacion', models.CharField(db_column='observacion', max_length=45)),
            ],
            options={
                'db_table': 'Compra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='detalle_compra',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(db_column='cantidad')),
            ],
            options={
                'db_table': 'detalle_compra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='detalle_venta',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(db_column='cantidad')),
                ('total_producto', models.IntegerField(db_column='total_producto')),
            ],
            options={
                'db_table': 'detalle_venta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=45)),
                ('stock', models.CharField(db_column='stock', max_length=45)),
                ('valor_costo', models.IntegerField(db_column='valor_costo')),
                ('valor_venta', models.IntegerField(db_column='valor_venta')),
                ('imagen', models.ImageField(db_column='imagen', upload_to=main.models.get_upload_path)),
                ('observacion', models.TextField(db_column='observacion')),
                ('descripcion', models.TextField(db_column='descripcion')),
            ],
            options={
                'db_table': 'Producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=45)),
                ('razon_social', models.CharField(db_column='razon_social', max_length=45)),
                ('telefono', models.CharField(db_column='telefono', max_length=45)),
                ('direccion', models.CharField(db_column='direccion', max_length=45)),
                ('celular', models.CharField(db_column='celular', max_length=45)),
            ],
            options={
                'db_table': 'Proveedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='descripcion', max_length=45)),
            ],
            options={
                'db_table': 'Rol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('telefono', models.IntegerField(db_column='telefono', null=True)),
            ],
            options={
                'db_table': 'Usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('fecha', models.DateField(db_column='fecha')),
                ('sub_total', models.IntegerField(db_column='sub_total')),
                ('total', models.IntegerField(db_column='total')),
                ('IVA', models.IntegerField(db_column='IVA')),
                ('observacion', models.CharField(db_column='observacion', max_length=45)),
            ],
            options={
                'db_table': 'Venta',
                'managed': False,
            },
        ),
    ]
