# Generated by Django 2.2.4 on 2021-02-06 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compra',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='detalle_compra',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='detalle_negocio_producto',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='detalle_usuario_negocio',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='detalle_venta',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='log',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='negocio',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='pabellon',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='unidad_medida',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='venta',
            options={'managed': False},
        ),
    ]
