# Generated by Django 2.2.2 on 2019-06-15 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='detalle_usuario_producto',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'detalle_usuario_producto',
                'managed': False,
            },
        ),
    ]
