# Generated by Django 2.2.4 on 2021-02-06 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210205_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_compra',
            name='cantidad_stock_anterior',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='detalle_compra',
            name='cantidad_stock_momento',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='detalle_venta',
            name='cantidad_stock_anterior',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='detalle_venta',
            name='cantidad_stock_momento',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='accion',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='negocio',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='usuario',
            field=models.IntegerField(null=True),
        ),
    ]
